name: Auto-Run Stock Analysis

on:
  push:
    branches: 
      - "run-analysis"
      - "run-bandar-analysis"
    paths:
      - '**.py'             
      - 'requirements.txt'   
      - '.github/workflows/**' 
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Python 3.10 is rock solid for pandas/numpy
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Analyze with Custom Flag
    - name: Analyze Stock 1
      run: python main.py ELSA --period 3y --balance 1000000
    - name: Analyze Stock 2
      run: python main.py MBMA --period 3y --balance 1000000
    - name: Analyze Stock 3
      run: python main.py PSAB --period 3y --balance 1000000
    - name: Analyze Stock 4
      run: python main.py AVIA --period 3y --balance 1000000
    - name: Analyze Stock 5
      run: python main.py HRUM --period 3y --balance 1000000




